# Servidor UTFPR (descomentar quando estiver na rede da UTFPR)
#spring.data.mongodb.uri=mongodb://develop-lds.td.utfpr.edu.br:27017/?directConnection=true
#spring.data.mongodb.database=agencia-noticias

# MongoDB Local / Container 
spring.data.mongodb.uri=mongodb://localhost:27017/agencia-noticias
#spring.data.mongodb.database=agencia-noticias

# Solr / Container
solr.url=http://localhost:8983/solr
solr.core=noticias

server.port=9091
server.servlet.context-path=/agencia.noticias
